blank_issues_enabled: false
contact_links:
  - name: Discord server
    url: https://discord.gg/pZrbJNb
    about: Please ask and answer questions here.
  - name: '@necauqua on Twitter'
    url: https://twitter.com/necauqua
    about: Follow for updates and stuff.
